---
host: idsc:IDS_CONNECTORS_ALL
openid: true
token:
  expiration: 3600
  signing_key: signing_key.pem
  algorithm: RS256
  audience: idsc:IDS_CONNECTORS_ALL
  issuer: http://omejdn:4567
id_token:
  expiration: 360000
  signing_key: signing_key.pem
  algorithm: RS256
  issuer: http://omejdn:4567
user_backend:
- yaml
