---
host: http://omejdn
accept_audience: idsc:IDS_CONNECTORS_ALL
openid: false
token:
  expiration: 3600
  signing_key: signing_key.key
  algorithm: RS256
  audience: idsc:IDS_CONNECTORS_ALL
  issuer: http://omejdn:4567
id_token:
  expiration: 360000
  signing_key: signing_key.key
  algorithm: RS256
  issuer: http://omejdn:4567
user_backend:
- yaml
user_backend_default: yaml
user_selfservice:
  enabled: false
  allow_deletion: false
  allow_password_change: false
  editable_attributes: []
path_prefix: ''
bind_to: 0.0.0.0
allow_origin: "*"
app_env: debug
issuer: http://omejdn:4567
front_url: http://localhost:4567
environment: '"development"'
default_audience: idsc:IDS_CONNECTORS_ALL
access_token:
  expiration: 3600
  algorithm: RS256
plugins:
  user_db:
    yaml: 
